before_all do
#  ENV["SLACK_URL"] = "https://hooks.slack.com/..."

  ensure_git_status_clean
  increment_build_number
  cocoapods
end

desc "Build and upload a binary"
lane :debug do
  # Build your app - more options available
  gym(configuration: 'Debug')

#  crashlytics(api_token: '1234567890abcdef',
#              build_secret: '1234567890abcdef1234567890abcdef',
#              crashlytics_path: "./Crashlytics.framework")

end

desc "Take snapshots"
lane :take_screenshots do
  snapshot(configuration: 'Debug')
end

# You can define as many lanes as you want

after_all do |lane|
  # This block is called, only if the executed lane was successful

  # Commit new build and push to git
  git_commit(message: "Version Bump", path: "./")
  add_git_tag
  push_to_git_remote

#    slack(message: "Successfully deployed new update.")
end

error do |lane, exception|
#    slack(
#      message: exception.message,
#      success: false
#    )
end
